import Link from "next/link";
import "./globals.css";
import Programs from "./programs/page";
import ProgramNavBtn from "./components/programNavBtn";
import GetAllPrograms from "./lib/getAllPrograms";
import Nav from "./components/nav";
import CenterDetail from "./components/centerDetail";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const 프로그램목록 = await GetAllPrograms();
  return (
    <html lang="en">
      <body>
        <header className="flex justify-between bg-orange-200">
          <h1>
            <Link href={"/"}>제목입니다</Link>
          </h1>
          <div>로고입니다.</div>
        </header>
        <section className="flex">
          <Nav />
          <div className="w-96">{children}</div>
          <div className="bg-red-300 border-r border-stone-300">
            <CenterDetail />
          </div>
          <div className="bg-blue-300 border-r border-stone-300">
            <Programs 프로그램목록={프로그램목록} />
          </div>
          <div className="bg-green-300">여기가 지도이미지</div>
        </section>
      </body>
    </html>
  );
}
