import Link from "next/link";
import "./globals.css";
import Programs from "./programs/page";
import ProgramNavBtn from "./components/programNavBtn";
import GetAllPrograms from "./lib/getAllPrograms";
import Nav from "./components/nav";
import CenterDetail from "./components/centerDetail";
import Header from "./components/header";

export const metadata = {
  title: "디디다: 충청남도 청소년 시설 자원 맵",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const 프로그램목록 = await GetAllPrograms();
  return (
    <html className="h-screen">
      <body className="h-screen font-NanumSquareRound">
        <Header />
        <section className="flex">
          <Nav />
          <main className="p-8 bg-white border-r w-80">{children}</main>
          <CenterDetail />
          <Programs 프로그램목록={프로그램목록} />
          <div className="bg-green-300">여기가 지도이미지</div>
        </section>
      </body>
    </html>
  );
}
